# Prometheus configuration for Trading Automation System
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Trading application metrics
  - job_name: 'trading-app'
    static_configs:
      - targets: ['trading-app:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Dashboard application metrics
  - job_name: 'trading-dashboard'
    static_configs:
      - targets: ['dashboard:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL metrics (using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis metrics (using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # System metrics (using node_exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s