import type { AlpacaAccount, AlpacaPosition } from '@trading-automation/shared';

export const OFFLINE_ACCOUNT: AlpacaAccount = {
  id: 'offline-account',
  status: 'ACTIVE',
  currency: 'USD',
  buying_power: '25000',
  regt_buying_power: '25000',
  daytrading_buying_power: '25000',
  cash: '5000',
  portfolio_value: '18500',
  pattern_day_trader: false,
  trading_blocked: false,
  transfers_blocked: false,
  account_blocked: false,
  crypto_status: 'inactive',
  shorting_enabled: false,
  long_market_value: '13500',
  short_market_value: '0',
  initial_margin: '0',
  maintenance_margin: '0',
  last_equity: '18000',
  last_maintenance_margin: '0',
  sma: '0',
};

export const OFFLINE_POSITIONS: AlpacaPosition[] = [
  {
    asset_id: 'offline-nvda',
    symbol: 'NVDA',
    exchange: 'NASDAQ',
    asset_class: 'us_equity',
    asset_marginable: true,
    qty: '5.50',
    avg_entry_price: '720.35',
    side: 'long',
    market_value: '3961.93',
    cost_basis: '3961.93',
    unrealized_pl: '525.37',
    unrealized_plpc: '0.153',
    unrealized_intraday_pl: '55.12',
    unrealized_intraday_plpc: '0.014',
    current_price: '720.35',
    lastday_price: '710.32',
    change_today: '0.014',
  },
  {
    asset_id: 'offline-aapl',
    symbol: 'AAPL',
    exchange: 'NASDAQ',
    asset_class: 'us_equity',
    asset_marginable: true,
    qty: '8.10',
    avg_entry_price: '182.40',
    side: 'long',
    market_value: '1481.44',
    cost_basis: '1477.44',
    unrealized_pl: '4.00',
    unrealized_plpc: '0.0027',
    unrealized_intraday_pl: '9.12',
    unrealized_intraday_plpc: '0.0062',
    current_price: '182.98',
    lastday_price: '181.85',
    change_today: '0.0062',
  },
  {
    asset_id: 'offline-msft',
    symbol: 'MSFT',
    exchange: 'NASDAQ',
    asset_class: 'us_equity',
    asset_marginable: true,
    qty: '3.25',
    avg_entry_price: '412.15',
    side: 'long',
    market_value: '1340.49',
    cost_basis: '1339.49',
    unrealized_pl: '1.00',
    unrealized_plpc: '0.0007',
    unrealized_intraday_pl: '6.50',
    unrealized_intraday_plpc: '0.0048',
    current_price: '412.46',
    lastday_price: '410.46',
    change_today: '0.0048',
  },
];
